[package]
org = "sameeragunarathne"
name = "v2_to_fhir_demo"
version = "0.1.0"
distribution = "2201.3.1"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "wso2healthcare"
name = "healthcare.hl7"
version = "0.1.6"

[[dependency]]
org = "wso2healthcare"
name = "healthcare.hl7v23"
version = "0.1.5"
